-- 會員續會/提醒功能用資料表
-- 使用方式：到 Supabase SQL Editor 貼上執行

-- participants 是否為會員（參加活動不一定等於入會）
alter table public.participants
  add column if not exists is_member boolean not null default false;

create index if not exists idx_participants_is_member on public.participants (is_member);

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 會員會籍主檔
create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  id_card text not null unique,
  effective_from date not null,
  expires_on date not null,
  next_due_on date not null,
  cycle_months integer not null default 1,
  status text not null default 'active' check (status in ('active','inactive')),
  last_renew_requested_at timestamptz,
  last_paid_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 若你已經建立過表，補上欄位
alter table public.memberships
  add column if not exists cycle_months integer not null default 1;

-- 參照 participants（若你的 participants.id_card 為主鍵/唯一鍵）
alter table public.memberships
  drop constraint if exists memberships_id_card_fkey;

alter table public.memberships
  add constraint memberships_id_card_fkey
  foreign key (id_card)
  references public.participants (id_card)
  on delete cascade;

drop trigger if exists trg_memberships_set_updated_at on public.memberships;
create trigger trg_memberships_set_updated_at
before update on public.memberships
for each row
execute function public.set_updated_at();

create index if not exists idx_memberships_next_due_on on public.memberships (next_due_on);
create index if not exists idx_memberships_expires_on on public.memberships (expires_on);

-- 每次續會申請紀錄（管理員審核用）
create table if not exists public.membership_renewal_requests (
  id bigint generated by default as identity primary key,
  membership_id bigint not null references public.memberships (id) on delete cascade,
  period_start date not null,
  period_end date not null,
  cycle_months integer not null default 1,
  requested_at timestamptz not null default now(),
  admin_status text not null default 'pending' check (admin_status in ('pending','paid','unpaid')),
  admin_updated_at timestamptz,
  admin_memo text,
  unique (membership_id, period_start)
);

-- 若你已經建立過表，補上欄位
alter table public.membership_renewal_requests
  add column if not exists cycle_months integer not null default 1;

create index if not exists idx_mrr_membership_id on public.membership_renewal_requests (membership_id);
create index if not exists idx_mrr_admin_status on public.membership_renewal_requests (admin_status);
create index if not exists idx_mrr_requested_at on public.membership_renewal_requests (requested_at desc);

-- 會員回覆紀錄（例如：本期回覆不續費）
create table if not exists public.membership_renewal_responses (
  id bigint generated by default as identity primary key,
  membership_id bigint not null references public.memberships (id) on delete cascade,
  period_start date not null,
  response text not null check (response in ('renew','decline')),
  cycle_months integer,
  responded_at timestamptz not null default now(),
  unique (membership_id, period_start)
);

-- 若你已經建立過表，補上欄位
alter table public.membership_renewal_responses
  add column if not exists cycle_months integer;

create index if not exists idx_mresp_response on public.membership_renewal_responses (response);
create index if not exists idx_mresp_responded_at on public.membership_renewal_responses (responded_at desc);

-- =============================
-- 自動帶入：participants -> memberships（規則 B：下月 1 號生效）
-- =============================

create or replace function public.ensure_membership_on_participant_insert()
returns trigger
language plpgsql
as $$
declare
  eff date;
  exp date;
  due date;
begin
  -- 參加活動不一定等於入會：只有 is_member=true 才自動建立會籍
  if coalesce(new.is_member, false) = false then
    return new;
  end if;

  -- 規則 B：有效日 = 下個月 1 號
  eff := (date_trunc('month', now()) + interval '1 month')::date;
  -- 到期日 = 有效日當月月底
  exp := (date_trunc('month', eff::timestamptz) + interval '1 month' - interval '1 day')::date;
  -- 應繳日 = 到期日 + 1 天
  due := (exp + 1);

  insert into public.memberships (id_card, effective_from, expires_on, next_due_on, cycle_months, status)
  values (new.id_card, eff, exp, due, 1, 'active')
  on conflict (id_card) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_participants_ensure_membership on public.participants;
create trigger trg_participants_ensure_membership
after insert on public.participants
for each row
execute function public.ensure_membership_on_participant_insert();

-- 回填：把既有 participants 但尚未建立 memberships 的人補齊（規則 B）
insert into public.memberships (id_card, effective_from, expires_on, next_due_on, cycle_months, status)
select
  p.id_card,
  (date_trunc('month', now()) + interval '1 month')::date as effective_from,
  (date_trunc('month', (date_trunc('month', now()) + interval '1 month')::date::timestamptz) + interval '1 month' - interval '1 day')::date as expires_on,
  ((date_trunc('month', (date_trunc('month', now()) + interval '1 month')::date::timestamptz) + interval '1 month' - interval '1 day')::date + 1) as next_due_on,
  1 as cycle_months,
  'active'
from public.participants p
left join public.memberships m on m.id_card = p.id_card
where m.id_card is null
  and p.is_member = true
  and coalesce(trim(p.id_card), '') <> ''
on conflict (id_card) do nothing;
