-- 會員續會/提醒功能用資料表
-- 使用方式：到 Supabase SQL Editor 貼上執行

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 會員會籍主檔
create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  id_card text not null unique,
  effective_from date not null,
  expires_on date not null,
  next_due_on date not null,
  status text not null default 'active' check (status in ('active','inactive')),
  last_renew_requested_at timestamptz,
  last_paid_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 參照 participants（若你的 participants.id_card 為主鍵/唯一鍵）
alter table public.memberships
  drop constraint if exists memberships_id_card_fkey;

alter table public.memberships
  add constraint memberships_id_card_fkey
  foreign key (id_card)
  references public.participants (id_card)
  on delete cascade;

drop trigger if exists trg_memberships_set_updated_at on public.memberships;
create trigger trg_memberships_set_updated_at
before update on public.memberships
for each row
execute function public.set_updated_at();

create index if not exists idx_memberships_next_due_on on public.memberships (next_due_on);
create index if not exists idx_memberships_expires_on on public.memberships (expires_on);

-- 每次續會申請紀錄（管理員審核用）
create table if not exists public.membership_renewal_requests (
  id bigint generated by default as identity primary key,
  membership_id bigint not null references public.memberships (id) on delete cascade,
  period_start date not null,
  period_end date not null,
  cycle_months integer not null default 1,
  requested_at timestamptz not null default now(),
  admin_status text not null default 'pending' check (admin_status in ('pending','paid','unpaid')),
  admin_updated_at timestamptz,
  admin_memo text,
  unique (membership_id, period_start)
);

-- 若你已經建立過表，補上欄位
alter table public.membership_renewal_requests
  add column if not exists cycle_months integer not null default 1;

create index if not exists idx_mrr_membership_id on public.membership_renewal_requests (membership_id);
create index if not exists idx_mrr_admin_status on public.membership_renewal_requests (admin_status);
create index if not exists idx_mrr_requested_at on public.membership_renewal_requests (requested_at desc);

-- 會員回覆紀錄（例如：本期回覆不續費）
create table if not exists public.membership_renewal_responses (
  id bigint generated by default as identity primary key,
  membership_id bigint not null references public.memberships (id) on delete cascade,
  period_start date not null,
  response text not null check (response in ('renew','decline')),
  cycle_months integer,
  responded_at timestamptz not null default now(),
  unique (membership_id, period_start)
);

-- 若你已經建立過表，補上欄位
alter table public.membership_renewal_responses
  add column if not exists cycle_months integer;

create index if not exists idx_mresp_response on public.membership_renewal_responses (response);
create index if not exists idx_mresp_responded_at on public.membership_renewal_responses (responded_at desc);
